protocol_mapping:
  Nucseq: rnaNucSeq.py;
  Nuc-seq: rnaNucSeq.py;


pipelines:
  rnaNucSeq.py:
    name: rnaNucSeq
    looper_args: True
    path: src/rnaNucSeq.py
    arguments:
      "--sample-name": sample_name
      "--genome": genome
      "--input": data_source
      "--single-or-paired": read_type
    optional_arguments:
      "--input2": read2
      # "--ercc-mix": ERCC_spikein
    required_input_files: [data_source]
    ngs_input_files: [data_source]    
    resources:
      default:
        file_size: "0"
        cores: "4"
        mem: "8000"
        time: "2-00:00:00"
      large:
        file_size: "4"
        cores: "6"
        mem: "16000"
        time: "2-00:00:00"

