# looper project definition. Instructions at http://looper.readthedocs.io

metadata:
  output_dir: ${HOME}/looper_test
  pipeline_interfaces: ${CODEBASE}rnapipe/pipeline_interface.yaml
  sample_annotation: example.csv

implied_columns:
  organism:
    "Homo sapiens":
      transcriptome: hg38_cdna
    "Mus musculus":
      transcriptome: mm10_cdna
      library: rnaKallisto

derived_columns: [data_source]

data_sources:
  SRA: "{sample_name}.bam"

pipeline_args:
  rnaKallisto.py:
    "-D": null
